name: Spring Boot CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  build-test-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build and run tests
        run: mvn clean test

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Automated PR from develop to main
          title: 'Merge develop into main'
          body: |
            This is an automated PR created by CI/CD pipeline.
            - Triggered by push to develop branch
            - Build and tests have passed
          branch: develop
          base: main
          draft: false

      - name: Auto-approve PR
        if: steps.create-pr.outputs.pull-request-number
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        if: steps.create-pr.outputs.pull-request-number
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ""
          MERGE_METHOD: "merge"
          MERGE_COMMIT_MESSAGE: "Auto-merge develop into main"
          MERGE_FILTER_AUTHOR: "github-actions[bot]"
          MERGE_DELETE_BRANCH: "false"
          MERGE_RETRY_SLEEP: "60000"
          PULL_REQUEST: ${{ steps.create-pr.outputs.pull-request-number }}